### ISSUE TITLE
[Bug] First try to add url to get error

### ISSUE THREAD

**Issue by hbakhtiyor** [run-llama/chat-llamaindex#18]
**To Reproduce**
1. Go to input text
2. Put url and press enter
3. See error

Second type without any errors
**Screenshots**
![image](https://github.com/run-llama/chat-llamaindex/assets/3434496/61e27af5-c10e-4f23-8ed7-9f7784c04e4d)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser edge
 - Version latest

**Comment by marcusschiesser** [comment]
@hbakhtiyor thanks for finding this. It's fixed in this commit: https://github.com/run-llama/chat-llamaindex/commit/889290bad215930469a05701be441d424f4c49f6
