### ISSUE TITLE
[Bug] Hit Token limit when using the generate command

### ISSUE THREAD

**Issue by cfortuner** [run-llama/chat-llamaindex#21]
**Describe the bug**

Ran into this when running the `generate <datasource` command.

```
BadRequestError: 400 This model's maximum context length is 8192 tokens, however you requested 18039 tokens (18039 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.
  error: {
    message: "This model's maximum context length is 8192 tokens, however you requested 18039 tokens (18039 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.",
    type: 'invalid_request_error',
    param: null,
    code: null
  },
```

I expected it to split the documents for me?

**Comment by marcusschiesser** [comment]
Yes, the `generate` script is splitting the documents by calling the `fromDocuments` function:
https://github.com/run-llama/chat-llamaindex/blob/df548a1918d476c5818b448cf75edd97feaa62d1/scripts/generate.mjs#L33-L37

The parameters for the splitting are set in the `constants.mjs` file:
https://github.com/run-llama/chat-llamaindex/blob/df548a1918d476c5818b448cf75edd97feaa62d1/scripts/constants.mjs#L3-L4

Your error message appears from a call to the OpenAI chat API, but the `generate` script should call the embeddings API. 
I would love to reproduce your error - what file types are in your `./datasources/{datasource}` directory before calling the `generate` command?

**Comment by aWN4Y25pa2EK** [comment]
This happened to me as well by could be due the fact that I've set `DATASOURCES_CHUNK_SIZE ` to `1024` is there any way to modify the openai `embedding` endpoint ?

**Comment by 54188wxp** [comment]
这种问题目前我还没有遇到，但是我觉得应该是一个逻辑错误

**Comment by swamichandra** [comment]
I'm facing the same issue as well. Especially on PDF's that are over 10MB in size. Would reducing the DATASOURCES_CHUNK_SIZE to say 384 or 256 help overcome this error? Anyone else found a way to resolve this error?

**Comment by j-cunanan** [comment]
Same issue here, and it is clearly hitting the embeddings endpoint. 

  headers: {
    'access-control-allow-origin': '*',
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8567709298405c04-NRT',
    connection: 'keep-alive',
    'content-length': '294',
    'content-type': 'application/json',
    date: 'Fri, 16 Feb 2024 17:16:41 GMT',
    'openai-model': 'text-embedding-3-small',
    ...
    
    My file is a 1hr transcript of a youtube video. It should not be a problem with chunking but somehow we get this error.
    
    ```error: {
    message: "This model's maximum context length is 8192 tokens, however you requested 11995 tokens (11995 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.",```
    
    I've also lowered the chunksize to 200 but nothing changed.
    
    The sample that worked is my 1 page PDF. So it might be with the `serviceContextFromDefaults` or `VectorStoreIndex.fromDocuments`?

**Comment by j-cunanan** [comment]
I fixed mine. 

I think the problem was that my text files did not have any punctuation marks!

So after modifying like this

`const textSplitter = new SentenceSplitter({ chunkSize: CHUNK_SIZE, splitLongSentences: true });
  const nodeParser = new SimpleNodeParser({
    chunkSize: CHUNK_SIZE,
    chunkOverlap: CHUNK_OVERLAP,
    textSplitter,
  });
  const serviceContext = serviceContextFromDefaults({
    nodeParser,
    embedModel: openaiEmbeds,
  });`
  
  It started generating

**Comment by marcusschiesser** [comment]
@j-cunanan yes, great catch. You need to use `splitLongSentences` in this case. For details have a look at: https://github.com/run-llama/LlamaIndexTS/issues/483

**Comment by CIB** [comment]
Can someone give more details please? "You need to use splitLongSentences" what does this even mean? I'm just trying to call the generate script, I don't have any custom code for this. And it seems that the actual splitting is happening in the llamaindex package. So do I have to modify the code in `node_modules/llamaindex`?
