### ISSUE TITLE
[Bug] deployement on aws amplify is not working properly

### ISSUE THREAD

**Issue by ada6597** [run-llama/chat-llamaindex#72]
**Describe the bug**
In local setup it's working fine , but when I deploy it to  aws amplify , it's giving internal server error (500) for API call

not it's calling this API : https://develop.d2tnt2s5bwrvl6.amplifyapp.com/api/llm 
instead of: http://localhost:300/api/llm

**To Reproduce**
Deploy it to aws amplify

**Expected behavior**
Should call api/llm successfully
**Screenshots**

**Deployment**
- [ ] aws amplify 

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser [chrome]

**Smartphone (please complete the following information):**

**Additional Logs**
Add any logs about the problem here.

**Comment by marcusschiesser** [comment]
Currently deployment to amplify is not supported, did you try Vercel?

**Comment by ada6597** [comment]
Hi @marcusschiesser,  Yes , tried on vercel it's working fine.

Letter on I found out that adding the env variable is a little bit different for aws amplify, made changes according to that , and it is Now working fine with aws amplify also.

Thanks for your reply!
