### ISSUE TITLE
Problems with uploading PDF files after update #76

### ISSUE THREAD

**Issue by faberfred** [run-llama/chat-llamaindex#78]
Problems with uploading PDF files after update #76. 
Uploading the identical file was working two days ago.

I am working on a Mac with Sonoma 14.2.1 and Chrome Version 122.0.6261.69

![Screenshot 2024-02-28 at 07 55 07](https://github.com/run-llama/chat-llamaindex/assets/38065373/4e43c719-4066-491c-84da-afad3c96001f)

**Comment by marcusschiesser** [comment]
Thanks for your bug report @faberfred - The issue is fixed please try again and reopen the ticket if you see any issues.
