### ISSUE TITLE
[Bug] Generating datasource not working anymore on the latest update

### ISSUE THREAD

**Issue by aprune168** [run-llama/chat-llamaindex#84]
**Describe the bug**
I'm using this project as a base for my site since last month and have just tried upgrading to the newest update (llamaindex edge).
Everything else seems fine but generating a datasource (pnpm run generate <datasource-name>) doesn't seem to be working anymore. (Tested on the original repository by cloning the latest update)
Error says: "Cannot find package 'llamaindex' imported from..."

+Additional bug:
https://chat.llamaindex.ai/
There is an error with the bots based off of data sources. (Red Hat Linux Expert, Apple Watch Genius, & German Basic Law Expert bots are not working.)

**To Reproduce**
1. Clone repository
2. Follow steps to create new data source (add folder to datasources folder -> add files to folder)
3. Run "pnpm run generate <folder-name>" in terminal

1. Go to [Chat Llamaindex](https://chat.llamaindex.ai/)
2. Select "German Basic Law Expert" bot
3. Ask any question

**Expected behavior**
A new VerctorStoreIndex for data source created (new data source folder and data in cache folder).
Normal chat experience at Chat Llamaindex site.

**Screenshots**
![스크린샷 2024-03-21 112228](https://github.com/run-llama/chat-llamaindex/assets/160823887/d59ec745-8813-4460-af7c-77b75d4e6b37)
![스크린샷 2024-03-21 132648](https://github.com/run-llama/chat-llamaindex/assets/160823887/7fb17cce-7112-4a9f-8b04-5e0e26aee295)

**Deployment**
- [ ] Docker
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):** Unapplicable

**Smartphone (please complete the following information):** Unapplicable

**Additional Logs** 
Add any logs about the problem here.

Thank you!!

**Comment by marcusschiesser** [comment]
@aprune168 thanks a lot for the report. We're working on this. Meanwhile please use the previous commit, see https://github.com/run-llama/chat-llamaindex/tree/7ed47c455bcad3088a7370d3d9ca1ef57ae0435d

**Comment by marcusschiesser** [comment]
@aprune168 I reverted that change due to https://github.com/run-llama/LlamaIndexTS/issues/662. Unfortunately, we would need to make a vector DB mandatory to keep Edge support. This complicates the usage of Chat LlamaIndex, therefore we're not adding Edge to it yet.

**Comment by aprune168** [comment]
@marcusschiesser Thank you so much for the quick response and processing!!
