### ISSUE TITLE
Deactivated GPT4 on chat.llamaindex.ai

### ISSUE THREAD

**Issue by StarRing2022** [run-llama/chat-llamaindex#91]
Dear friends, I regret to inform you that Chatlamaindex's response has been invalidated

{
  "error": true,
  "message": "There was an error calling the OpenAI API. Please try again later."
}

**Comment by marcusschiesser** [comment]
Sorry for the trouble @StarRing2022 

All of the demo bots have been using GPT4, and we deactivated support for GPT4 on https://chat.llamaindex.ai/ 

As the demo bots are stored in your local browser, please click on "Clear All Data" on the [settings](https://chat.llamaindex.ai/#/settings) page:

<img width="1463" alt="image" src="https://github.com/run-llama/chat-llamaindex/assets/17126/ff9a21fb-af11-46e1-ad8e-ea0c9b0b838b">

This will re-create the demo bots using GPT 3.5. 

You can still use GPT4 on your local deployment of chat llamaindex. The `ALLOW_ALL_MODELS` env variable controls the behavior, which is set to `TRUE` by default.

**Comment by StarRing2022** [comment]
Thanks,Give best wishes
