### ISSUE TITLE
[Bug]  Docker Build is not working

### ISSUE THREAD

**Issue by luancaarvalho** [run-llama/chat-llamaindex#95]
**Describe the bug**
The docker build command described at the readme is not working 

**To Reproduce**
1. Just run the docker build

**Expected behavior**

**Deployment**
- [ X] Docker Desktop - v4.17.0
- [ ] Vercel
- [ ] Server

**Desktop (please complete the following information):**
 - OS: [Mac os]

**Additional Logs**
=> ERROR [build 6/8] RUN npm install -g pnpm &&     pnpm install         36.8s
------
 > [build 6/8] RUN npm install -g pnpm &&     pnpm install:
#11 2.817 
#11 2.817 added 1 package in 3s
#11 2.817 
#11 2.817 1 package is looking for funding
#11 2.817   run `npm fund` for details
#11 2.819 npm notice
#11 2.819 npm notice New minor version of npm available! 10.7.0 -> 10.8.1
#11 2.819 npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.1
#11 2.819 npm notice To update run: npm install -g npm@10.8.1
#11 2.819 npm notice
#11 3.464 Lockfile is up to date, resolution step is skipped
#11 3.590 Progress: resolved 1, reused 0, downloaded 0, added 0
#11 3.984 Packages: +1239
#11 3.984 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#11 4.603 Progress: resolved 1239, reused 0, downloaded 10, added 8
#11 5.604 Progress: resolved 1239, reused 0, downloaded 56, added 56
#11 6.605 Progress: resolved 1239, reused 0, downloaded 91, added 91
#11 7.605 Progress: resolved 1239, reused 0, downloaded 132, added 131
#11 8.631 Progress: resolved 1239, reused 0, downloaded 179, added 179
#11 9.631 Progress: resolved 1239, reused 0, downloaded 239, added 239
#11 10.63 Progress: resolved 1239, reused 0, downloaded 302, added 302
#11 11.63 Progress: resolved 1239, reused 0, downloaded 335, added 335
#11 12.63 Progress: resolved 1239, reused 0, downloaded 344, added 344
#11 13.64 Progress: resolved 1239, reused 0, downloaded 363, added 363
#11 14.64 Progress: resolved 1239, reused 0, downloaded 405, added 405
#11 15.64 Progress: resolved 1239, reused 0, downloaded 440, added 440
#11 16.64 Progress: resolved 1239, reused 0, downloaded 468, added 468
#11 17.64 Progress: resolved 1239, reused 0, downloaded 495, added 494
#11 18.64 Progress: resolved 1239, reused 0, downloaded 527, added 527
#11 19.65 Progress: resolved 1239, reused 0, downloaded 556, added 556
#11 20.65 Progress: resolved 1239, reused 0, downloaded 586, added 586
#11 21.65 Progress: resolved 1239, reused 0, downloaded 616, added 616
#11 22.65 Progress: resolved 1239, reused 0, downloaded 659, added 659
#11 23.65 Progress: resolved 1239, reused 0, downloaded 718, added 718
#11 24.65 Progress: resolved 1239, reused 0, downloaded 782, added 782
#11 25.65 Progress: resolved 1239, reused 0, downloaded 816, added 816
#11 26.65 Progress: resolved 1239, reused 0, downloaded 837, added 836
#11 27.65 Progress: resolved 1239, reused 0, downloaded 873, added 873
#11 28.65 Progress: resolved 1239, reused 0, downloaded 949, added 949
#11 29.66 Progress: resolved 1239, reused 0, downloaded 993, added 993
#11 30.66 Progress: resolved 1239, reused 0, downloaded 1079, added 1079
#11 31.66 Progress: resolved 1239, reused 0, downloaded 1166, added 1166
#11 32.72 Progress: resolved 1239, reused 0, downloaded 1206, added 1205
#11 33.71 Progress: resolved 1239, reused 0, downloaded 1237, added 1237
#11 34.07 Progress: resolved 1239, reused 0, downloaded 1239, added 1239, done
#11 34.63 .../node_modules/protobufjs postinstall$ node scripts/postinstall
#11 34.67 .../node_modules/bufferutil install$ node-gyp-build
#11 34.67 .../node_modules/utf-8-validate install$ node-gyp-build
#11 34.67 .../node_modules/@sentry/cli install$ node ./scripts/install.js
#11 34.73 .../esbuild@0.21.5/node_modules/esbuild postinstall$ node install.js
#11 34.77 .../node_modules/protobufjs postinstall: Done
#11 34.91 .../node_modules/protobufjs postinstall$ node scripts/postinstall
#11 34.95 .../node_modules/@sentry/cli install: [sentry-cli] Downloading from https://downloads.sentry-cdn.com/sentry-cli/1.77.3/sentry-cli-Linux-aarch64
#11 35.01 .../esbuild@0.21.5/node_modules/esbuild postinstall: Done
#11 35.03 .../node_modules/protobufjs postinstall: Done
#11 35.03 .../node_modules/utf-8-validate install: gyp info it worked if it ends with ok
#11 35.03 .../node_modules/utf-8-validate install: gyp info using node-gyp@10.1.0
#11 35.03 .../node_modules/utf-8-validate install: gyp info using node@18.20.3 | linux | arm64
#11 35.07 .../sharp@0.32.6/node_modules/sharp install$ (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
#11 35.11 .../node_modules/bufferutil install: gyp info it worked if it ends with ok
#11 35.11 .../node_modules/bufferutil install: gyp info using node-gyp@10.1.0
#11 35.11 .../node_modules/bufferutil install: gyp info using node@18.20.3 | linux | arm64
#11 35.17 .../node_modules/utf-8-validate install: gyp ERR! find Python 
#11 35.18 .../node_modules/utf-8-validate install: gyp ERR! find Python Python is not set from command line or npm configuration
#11 35.18 .../node_modules/utf-8-validate install: gyp ERR! find Python Python is not set from environment variable PYTHON
#11 35.18 .../node_modules/utf-8-validate install: gyp ERR! find Python checking if "python3" can be used
#11 35.18 .../node_modules/utf-8-validate install: gyp ERR! find Python - executable path is ""
#11 35.18 .../node_modules/utf-8-validate install: gyp ERR! find Python - "" could not be run
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python checking if "python" can be used
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python - executable path is ""
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python - "" could not be run
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python 
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python **********************************************************
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python You need to install the latest version of Python.
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python you can try one of the following options:
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python (accepted by both node-gyp and npm)
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python - Set the environment variable PYTHON
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python - Set the npm configuration variable python:
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python For more information consult the documentation at:
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python **********************************************************
#11 35.19 .../node_modules/utf-8-validate install: gyp ERR! find Python 
#11 35.20 .../node_modules/utf-8-validate install: gyp ERR! configure error 
#11 35.20 .../node_modules/utf-8-validate install: gyp ERR! stack Error: Could not find any Python installation to use
#11 35.20 .../node_modules/utf-8-validate install: gyp ERR! stack at PythonFinder.fail (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:306:11)
#11 35.20 .../node_modules/utf-8-validate install: gyp ERR! stack at PythonFinder.findPython (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/find-python.js:164:17)
#11 35.20 .../node_modules/utf-8-validate install: gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
#11 35.20 .../node_modules/utf-8-validate install: gyp ERR! stack at async configure (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/lib/configure.js:27:18)
#11 35.20 .../node_modules/utf-8-validate install: gyp ERR! stack at async run (/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js:81:18)
#11 35.20 .../node_modules/utf-8-validate install: gyp ERR! System Linux 5.15.49-linuxkit
#11 35.20 .../node_modules/utf-8-validate install: gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#11 35.20 .../node_modules/utf-8-validate install: gyp ERR! cwd /usr/src/app/node_modules/.pnpm/utf-8-validate@6.0.4/node_modules/utf-8-validate
#11 35.21 .../node_modules/utf-8-validate install: gyp ERR! node -v v18.20.3
#11 35.21 .../node_modules/utf-8-validate install: gyp ERR! node-gyp -v v10.1.0
#11 35.21 .../node_modules/utf-8-validate install: gyp ERR! not ok 
#11 35.25 .../node_modules/utf-8-validate install: Failed
#11 35.25  ELIFECYCLE  Command failed with exit code 1.
------
executor failed running [/bin/sh -c npm install -g pnpm &&     pnpm install]: exit code: 1

**Comment by marcusschiesser** [comment]
@luancaarvalho please try latest `main`
